docs_dir: 'content'
site_name: 'RBKmoney|docs'
repo_url: https://github.com/rbkmoney/docs
theme: 'material'
theme_dir: 'theme'
extra:
    palette:
        primary: green
        accent: lime
    links:
        'API reference': 
            url: 'https://rbkmoney.github.io/api/'
            target: _blank
extra_css:
    - 'assets/stylesheets/override.css'
    - 'livedemo/livedemo.css'
    - 'livedemo/loader.css'
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'
    - 'livedemo/livedemo.js'
    - 'counters/ga.js'
    - 'counters/ym.js'
strict: true
markdown_extensions:
    - smarty
    - admonition
    - def_list
    - footnotes
    - codehilite
    - toc:
        permalink: true
pages:
    - 'Документация': 'index.md'
    - 'Интеграция':
        - 'Обзор': 'integrations/overview.md'
        - 'Checkout': 'integrations/checkout.md'
        - 'Tokenizer': 'integrations/tokenizer.md'
        - 'Postman': 'integrations/postman.md'
    - 'Справочники':
        - 'Тестовые карты': 'refs/testcards.md'
