docs_dir: 'content'
site_name: 'RBKmoney|docs'
repo_url: https://github.com/rbkmoney/docs
theme:
    name: material
    custom_dir: theme
extra:
    palette:
        primary: green
        accent: lime
    links:
        'API reference':
            url: 'https://rbkmoney.github.io/api/'
            target: _blank
extra_css:
    - 'assets/stylesheets/override.css'
    - 'lightbox/css/lightbox.min.css'
    - 'livedemo/livedemo.css'
extra_javascript:
    - 'lightbox/js/lightbox-plus-jquery.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'
    - 'https://checkout.rbk.money/checkout.js'
    - 'livedemo/livedemo.js'
    - 'counters/ga.js'
    - 'counters/ym.js'
strict: true
markdown_extensions:
    - smarty
    - admonition
    - def_list
    - footnotes
    - codehilite
    - toc:
        permalink: true
pages:
    - 'Документация': 'index.md'
    - 'Интеграция':
        - 'Обзор': 'integrations/overview.md'
        - 'Checkout': 'integrations/checkout.md'
        - 'Tokenizer': 'integrations/tokenizer.md'
        - '3D-Secure': 'integrations/3dsecure.md'
        - 'Recurring': 'integrations/recurring.md'
        - 'Postman': 'integrations/postman.md'
        - 'Примеры':
            - 'PHP and Checkout': 'integrations/examples/php-kkt-cart-webhooks.md'
        - 'Модули CMS':
            - 'Bitrix': 'integrations/cms-modules/bitrix/index.md'
            - 'InSales': 'integrations/cms-modules/insales/index.md'
            - 'Webasyst/ShopScript': 'integrations/cms-modules/webasyst/index.md'
            - 'Wordpress/Woocommerce': 'integrations/cms-modules/woocommerce/index.md'
            - 'Wordpress/E-commerce': 'integrations/cms-modules/wp-e-commerce/index.md'
            - 'Opencart': 'integrations/cms-modules/opencart/index.md'
            - 'Netcat': 'integrations/cms-modules/netcat/index.md'
            - 'Prestashop': 'integrations/cms-modules/prestashop/index.md'
            - 'Drupal/Ubercart': 'integrations/cms-modules/ubercart/index.md'
            - 'Drupal/Commerce': 'integrations/cms-modules/drupal-commerce/index.md'
            - 'Magento': 'integrations/cms-modules/magento/index.md'
            - 'Joomla/Virtuemart': 'integrations/cms-modules/virtuemart/index.md'
    - 'Справочники':
        - 'Тестовые карты': 'refs/testcards.md'
    - 'API': 'api.md'