docs_dir: 'content'
site_name: 'RBKmoney|docs'
repo_url: https://github.com/rbkmoney/docs
theme:
    name: material
    custom_dir: theme
extra:
    links:
        'Payments API':
            url: 'https://developer.rbk.money/api/'
            target: _blank
        'Wallets API':
            url: 'https://rbkmoney.github.io/wallets-api/v0/'
            target: _blank
        'Identity Storage API':
            url: 'https://rbkmoney.github.io/wallets-api/v0/?api/privdoc/swagger.json'
            target: _blank
extra_css:
    - 'assets/stylesheets/override.css'
    - '/docs/lightbox/css/lightbox.min.css'
    - '/docs/payments/livedemo/livedemo.css'
extra_javascript:
    - 'https://code.jquery.com/jquery-3.3.1.min.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'
    - 'https://checkout.rbk.money/checkout.js'
    - '/docs/payments/livedemo/livedemo.js'
    - '/docs/lightbox/js/lightbox.min.js'
strict: true
markdown_extensions:
    - smarty
    - admonition
    - def_list
    - footnotes
    - codehilite
    - toc:
        permalink: true
nav:
    - 'Документация': 'index.md'
    - 'Интеграция':
        - Payments:
            - 'Обзор': 'docs/payments/overview.md'
            - 'Checkout': 'docs/payments/checkout.md'
            - 'Tokenizer': 'docs/payments/tokenizer.md'
            - '3D-Secure': 'docs/payments/3dsecure.md'
            - 'Recurring': 'docs/payments/recurring.md'
            - 'Postman': 'docs/payments/postman.md'
            - 'Google Pay': 'docs/payments/googlepay/index.md'
            - 'Apple Pay': 'docs/payments/applepay/index.md'
            - 'Примеры':
                - 'PHP and Checkout': 'docs/payments/examples/php-kkt-cart-webhooks.md'
                - 'Node.js верификация webhook': 'docs/payments/examples/nodejs-webhook-verification.md'
            - 'Модули CMS':
                - 'Bitrix': 'docs/payments/cms-modules/bitrix/index.md'
                - 'InSales': 'docs/payments/cms-modules/insales/index.md'
                - 'Webasyst/ShopScript': 'docs/payments/cms-modules/webasyst/index.md'
                - 'Wordpress/Woocommerce': 'docs/payments/cms-modules/woocommerce/index.md'
                - 'Wordpress/E-commerce': 'docs/payments/cms-modules/wp-e-commerce/index.md'
                - 'Opencart': 'docs/payments/cms-modules/opencart/index.md'
                - 'Netcat': 'docs/payments/cms-modules/netcat/index.md'
                - 'Prestashop': 'docs/payments/cms-modules/prestashop/index.md'
                - 'Drupal/Ubercart': 'docs/payments/cms-modules/ubercart/index.md'
                - 'Drupal/Commerce': 'docs/payments/cms-modules/drupal-commerce/index.md'
                - 'Magento': 'docs/payments/cms-modules/magento/index.md'
                - 'Joomla/Virtuemart': 'docs/payments/cms-modules/virtuemart/index.md'
        - Wallets:
                - 'Обзор': 'docs/wallets/overview.md'
                - 'Работа с кошельками': 'docs/wallets/usage/index.md'
                - 'Выплаты на карты': 'docs/wallets/card-payouts/index.md'
    - 'Справочники':
        - 'Тестовые карты': 'docs/payments/refs/testcards.md'
